version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: my_mysql
    environment:
      MYSQL_ROOT_PASSWORD: yy20040706
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    networks:
      - my_network
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: my_redis
    environment:
      REDIS_PASSWORD: yy20040706
      TZ: Asia/Shanghai
    ports:
      - "6379:6379"
    networks:
      - my_network
    volumes:
      - redis_data:/data
    command: redis-server --requirepass yy20040706

  rabbitmq:
    image: rabbitmq:management
    container_name: my_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: wyy
      RABBITMQ_DEFAULT_PASS: yy20040706
      TZ: Asia/Shanghai
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my_network

  gin_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_gin_app
    environment:
      GOPROXY: https://goproxy.cn,direct
      TZ: Asia/Shanghai
    restart: always
    privileged: true
    ports:
      - "9000:9000"
    networks:
      - my_network
    depends_on:
      - mysql
      - redis
      - rabbitmq
    volumes:
      - ./:/app

networks:
  my_network:

volumes:
  mysql_data:
  redis_data: